
import React, { useState, useEffect } from 'react';
import { storageService } from '../services/storage';
import { JournalEntry } from '../types';
import { PenTool, Plus, X, Calendar, Trash2, Loader2, Maximize2, AlertCircle } from 'lucide-react';

export const Journal: React.FC = () => {
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isComposing, setIsComposing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  // New State for View & Delete
  const [selectedEntry, setSelectedEntry] = useState<JournalEntry | null>(null);
  const [entryToDelete, setEntryToDelete] = useState<string | null>(null);

  const [newTitle, setNewTitle] = useState('');
  const [newContent, setNewContent] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    loadEntries();
  }, []);

  const loadEntries = async () => {
    const data = await storageService.getJournalEntries();
    setEntries(data);
    setIsLoading(false);
  };

  const handleSave = async () => {
    setError('');
    
    // 1. Sanitization: Trim whitespace
    const cleanTitle = newTitle.trim();
    const cleanContent = newContent.trim();

    if (!cleanTitle || !cleanContent) {
        setError('يرجى ملء جميع الحقول');
        return;
    }

    // 2. Validation: Length Limits (Prevents Data Stuffing)
    if (cleanTitle.length > 100) {
        setError('العنوان طويل جداً (الحد الأقصى 100 حرف)');
        return;
    }
    
    // 3. Validation: Content Length (Reasonable limit for a JSON blob)
    if (cleanContent.length > 5000) {
        setError('المحتوى طويل جداً (الحد الأقصى 5000 حرف)');
        return;
    }

    setIsSaving(true);

    const entry: JournalEntry = {
      id: '', // Generated by DB
      title: cleanTitle, // Store sanitized title
      content: cleanContent, // Store sanitized content
      date: new Date().toLocaleDateString('ar-SA'),
      mood: 'reflecting'
    };

    try {
        const updated = await storageService.addJournalEntry(entry);
        setEntries(updated);
        setIsSaving(false);
        setIsComposing(false);
        setNewTitle('');
        setNewContent('');
    } catch (e) {
        console.error(e);
        setError('حدث خطأ أثناء الحفظ');
        setIsSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!entryToDelete) return;
    setIsLoading(true);
    const updated = await storageService.deleteJournalEntry(entryToDelete);
    setEntries(updated);
    setIsLoading(false);
    setEntryToDelete(null);
    setSelectedEntry(null); // Close view if deleted from view
  };

  return (
    <div className="pb-24 pt-6 space-y-6 px-4 h-full flex flex-col">
      <div className="flex items-center justify-between">
         <div>
            <h2 className="text-2xl font-bold text-white">خواطري</h2>
            <p className="text-xs text-slate-400">مساحتك الخاصة للتأمل والدعاء</p>
         </div>
         <button 
           onClick={() => setIsComposing(true)}
           className="bg-emerald-600 hover:bg-emerald-500 text-white p-3 rounded-full shadow-lg shadow-emerald-900/50 transition-all active:scale-95"
         >
           <Plus size={24} />
         </button>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-20">
           <Loader2 className="animate-spin text-emerald-500" size={32} />
        </div>
      ) : entries.length === 0 && !isComposing ? (
        <div className="flex flex-col items-center justify-center py-20 text-slate-500 opacity-60">
           <PenTool size={48} className="mb-4" />
           <p>لا توجد خواطر مسجلة بعد</p>
           <p className="text-sm">ابدأ بتدوين مشاعرك في هذا الشهر الفضيل</p>
        </div>
      ) : (
        <div className="space-y-3">
           {entries.map(entry => (
             <div 
                key={entry.id} 
                onClick={() => setSelectedEntry(entry)}
                className="glass-panel rounded-2xl p-5 border-r-4 border-emerald-500 cursor-pointer hover:bg-white/5 transition-colors group relative"
             >
                <div className="flex justify-between items-start mb-2">
                   <h3 className="font-bold text-lg text-white">{entry.title}</h3>
                   <div className="flex items-center gap-3">
                      <span className="text-[10px] text-slate-400 bg-slate-800 px-2 py-1 rounded-full flex items-center gap-1">
                        <Calendar size={10} />
                        {entry.date}
                      </span>
                   </div>
                </div>
                <p className="text-slate-300 text-sm leading-relaxed whitespace-nowrap overflow-hidden text-ellipsis opacity-80">
                  {entry.content}
                </p>
                
                {/* Expand Hint */}
                <div className="absolute bottom-3 left-3 opacity-0 group-hover:opacity-100 transition-opacity text-emerald-400">
                    <Maximize2 size={16} />
                </div>
             </div>
           ))}
        </div>
      )}

      {/* --- CONFIRM DELETE MODAL --- */}
      {entryToDelete && (
          <div className="fixed inset-0 z-[200] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
              <div className="bg-slate-900 border border-red-500/30 w-full max-w-sm rounded-3xl p-6 text-center shadow-2xl animate-in zoom-in-95 duration-200">
                  <div className="w-16 h-16 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-4 text-red-500">
                      <AlertCircle size={32} />
                  </div>
                  <h3 className="text-xl font-bold text-white mb-2">تأكيد الحذف</h3>
                  <p className="text-sm text-slate-400 mb-6">هل أنت متأكد من حذف هذه الخاطرة؟ لا يمكن التراجع عن هذا الإجراء.</p>
                  <div className="flex gap-3">
                      <button 
                        onClick={() => setEntryToDelete(null)}
                        className="flex-1 py-3 rounded-xl bg-slate-800 text-white font-bold hover:bg-slate-700 transition-colors"
                      >
                        إلغاء
                      </button>
                      <button 
                        onClick={confirmDelete}
                        className="flex-1 py-3 rounded-xl bg-red-600 text-white font-bold hover:bg-red-500 transition-colors shadow-lg shadow-red-900/20"
                      >
                        حذف
                      </button>
                  </div>
              </div>
          </div>
      )}

      {/* --- VIEW ENTRY MODAL --- */}
      {selectedEntry && (
        <div className="fixed inset-0 z-[150] bg-black/90 backdrop-blur-md flex items-center justify-center p-4">
           <div className="bg-slate-900 w-full max-w-lg h-[80vh] flex flex-col rounded-3xl border border-slate-700 shadow-2xl overflow-hidden animate-in slide-in-from-bottom-10 fade-in duration-300">
               {/* Header */}
               <div className="p-5 border-b border-slate-800 flex justify-between items-start bg-slate-800/30">
                 <div>
                    <h3 className="font-bold text-xl text-white mb-1">{selectedEntry.title}</h3>
                    <div className="flex items-center gap-2 text-xs text-emerald-400">
                        <Calendar size={12} />
                        <span>{selectedEntry.date}</span>
                    </div>
                 </div>
                 <button onClick={() => setSelectedEntry(null)} className="p-2 bg-slate-800 rounded-full text-slate-400 hover:text-white">
                    <X size={20}/>
                 </button>
               </div>
               
               {/* Content */}
               <div className="flex-1 overflow-y-auto custom-scrollbar p-6">
                  <p className="text-slate-200 text-base leading-loose whitespace-pre-wrap font-serif">
                     {selectedEntry.content}
                  </p>
               </div>

               {/* Footer / Actions */}
               <div className="p-4 border-t border-slate-800 bg-slate-800/30 flex justify-end">
                  <button 
                    onClick={() => setEntryToDelete(selectedEntry.id)}
                    className="flex items-center gap-2 text-red-400 hover:text-red-300 px-4 py-2 rounded-xl hover:bg-red-500/10 transition-colors"
                  >
                     <Trash2 size={18} />
                     <span>حذف الخاطرة</span>
                  </button>
               </div>
           </div>
        </div>
      )}

      {/* --- COMPOSE MODAL --- */}
      {isComposing && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[100] flex items-end sm:items-center justify-center p-4">
           <div className="bg-slate-900 w-full max-w-lg rounded-3xl border border-slate-700 shadow-2xl overflow-hidden animate-in slide-in-from-bottom-10 fade-in duration-300">
              <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-800/50">
                 <h3 className="font-bold text-white">خاطرة جديدة</h3>
                 <button onClick={() => setIsComposing(false)} className="text-slate-400 hover:text-white"><X size={20}/></button>
              </div>
              
              {error && (
                 <div className="bg-red-500/10 text-red-300 p-2 text-center text-xs border-b border-red-500/20">
                    {error}
                 </div>
              )}

              <div className="p-4 space-y-4">
                 <input
                   autoFocus
                   type="text"
                   placeholder="عنوان الخاطرة (مثلاً: شعور أول يوم رمضان)"
                   value={newTitle}
                   onChange={(e) => setNewTitle(e.target.value)}
                   maxLength={100}
                   className="w-full bg-slate-950/50 border border-slate-700 rounded-xl p-3 text-white placeholder-slate-500 focus:border-emerald-500 focus:outline-none transition-colors"
                 />
                 <textarea
                   placeholder="اكتب ما يجول في خاطرك..."
                   value={newContent}
                   onChange={(e) => setNewContent(e.target.value)}
                   rows={8}
                   maxLength={5000}
                   className="w-full bg-slate-950/50 border border-slate-700 rounded-xl p-3 text-white placeholder-slate-500 focus:border-emerald-500 focus:outline-none transition-colors resize-none custom-scrollbar"
                 />
                 <button 
                    onClick={handleSave}
                    disabled={isSaving}
                    className="w-full bg-gradient-to-r from-emerald-600 to-emerald-500 text-white font-bold py-3 rounded-xl shadow-lg hover:shadow-emerald-500/20 active:scale-95 transition-all flex items-center justify-center gap-2"
                 >
                    {isSaving && <Loader2 size={16} className="animate-spin" />}
                    حفظ الخاطرة
                 </button>
              </div>
           </div>
        </div>
      )}
    </div>
  );
};
